theme: jekyll-theme-minimal
title: Focus Homebuyers
description: Bookmark this to keep an eye on my project updates!
exclude: notes.txt
collections:
  locations:
    output: true
    collection: locations
    layout: marketing
